// <auto-generated />
namespace Btth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_comlumn_Student_Address : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_comlumn_Student_Address));
        
        string IMigrationMetadata.Id
        {
            get { return "202109280154012_add_comlumn_Student_Address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
